// <auto-generated />
using System;
using GerenciadorDeTarefas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GerenciadorDeTarefas.Migrations
{
    [DbContext(typeof(SistemaDeTarefaDBContext))]
    [Migration("20251219140755_AddEnumsToTarefa")]
    partial class AddEnumsToTarefa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "prioridade", new[] { "todas", "alta", "media", "baixa" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status", new[] { "aberta", "concluida" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GerenciadorDeTarefas.Models.ProjetoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioModelId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioNome")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioModelId");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Models.TagModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<int?>("ProjetoModelId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoModelId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Models.TarefaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PrioridadeTarefa")
                        .HasColumnType("prioridade_enum");

                    b.Property<int?>("ProjetoId")
                        .HasColumnType("integer");

                    b.Property<int?>("StatusTarefa")
                        .HasColumnType("status_enum");

                    b.Property<string>("Titulo")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Models.UsuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("TagModelTarefaModel", b =>
                {
                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.Property<int>("TarefasId")
                        .HasColumnType("integer");

                    b.HasKey("TagsId", "TarefasId");

                    b.HasIndex("TarefasId");

                    b.ToTable("TagModelTarefaModel");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Models.ProjetoModel", b =>
                {
                    b.HasOne("GerenciadorDeTarefas.Models.UsuarioModel", null)
                        .WithMany("Projetos")
                        .HasForeignKey("UsuarioModelId");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Models.TagModel", b =>
                {
                    b.HasOne("GerenciadorDeTarefas.Models.ProjetoModel", null)
                        .WithMany("Tags")
                        .HasForeignKey("ProjetoModelId");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Models.TarefaModel", b =>
                {
                    b.HasOne("GerenciadorDeTarefas.Models.ProjetoModel", "Projeto")
                        .WithMany("Tarefas")
                        .HasForeignKey("ProjetoId");

                    b.HasOne("GerenciadorDeTarefas.Models.UsuarioModel", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projeto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TagModelTarefaModel", b =>
                {
                    b.HasOne("GerenciadorDeTarefas.Models.TagModel", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciadorDeTarefas.Models.TarefaModel", null)
                        .WithMany()
                        .HasForeignKey("TarefasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Models.ProjetoModel", b =>
                {
                    b.Navigation("Tags");

                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("GerenciadorDeTarefas.Models.UsuarioModel", b =>
                {
                    b.Navigation("Projetos");

                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
